### ISSUE TITLE
E2M2 displays Red Keycard as requiring Red Keycard

### ISSUE THREAD

**Issue by nivomi** [Ozone31/doom-ap-tracker#2]
![image](https://github.com/Ozone31/doom-ap-tracker/assets/651417/40640dec-1c92-4114-b5bc-16bed2363349)

Logic is operating correctly - it shows as inaccessible when I have R, Y, but not B - but the displayed message on the tooltip is incorrect.

**Comment by Ozone31** [comment]
This is now fixed in v0.0.2.5. Thanks for letting me know!
